// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD32-44YLU2dV05OWliPtx2uLJ9Qi2cxy4',
    appId: '1:949227164224:web:810e9a420c313cd2f005a5',
    messagingSenderId: '949227164224',
    projectId: 'saffroneshwar-4b0d7',
    authDomain: 'saffroneshwar-4b0d7.firebaseapp.com',
    storageBucket: 'saffroneshwar-4b0d7.appspot.com',
    measurementId: 'G-0286JBX3Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArDXsLugpMuoRHjJadTl34B-wT5bV9UbY',
    appId: '1:949227164224:android:4b10c9f5202faf1cf005a5',
    messagingSenderId: '949227164224',
    projectId: 'saffroneshwar-4b0d7',
    storageBucket: 'saffroneshwar-4b0d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbO1YgTciTQ8cYlMYGLfy58w-NDcjOrMA',
    appId: '1:949227164224:ios:002825f5eaa8f301f005a5',
    messagingSenderId: '949227164224',
    projectId: 'saffroneshwar-4b0d7',
    storageBucket: 'saffroneshwar-4b0d7.appspot.com',
    iosBundleId: 'com.example.giphyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbO1YgTciTQ8cYlMYGLfy58w-NDcjOrMA',
    appId: '1:949227164224:ios:002825f5eaa8f301f005a5',
    messagingSenderId: '949227164224',
    projectId: 'saffroneshwar-4b0d7',
    storageBucket: 'saffroneshwar-4b0d7.appspot.com',
    iosBundleId: 'com.example.giphyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD32-44YLU2dV05OWliPtx2uLJ9Qi2cxy4',
    appId: '1:949227164224:web:7ae36a88c48367d8f005a5',
    messagingSenderId: '949227164224',
    projectId: 'saffroneshwar-4b0d7',
    authDomain: 'saffroneshwar-4b0d7.firebaseapp.com',
    storageBucket: 'saffroneshwar-4b0d7.appspot.com',
    measurementId: 'G-C8CMYN1X06',
  );

}